name: actionFromMarketPlace
on: push
jobs:
  job1:
    name: Job for using action from marketplace
    runs-on: ubuntu-latest
    steps:
          - name: Download a Build Artifact
            uses: actions/download-artifact@v7.0.0
            
                  
